Name = input("Nama : ")
NIM = input("NIM : ")
Class = input("Kelas Paralel : ")
TTL = input("Tempat/Tanggal Lahir : ")
Address = input("Alamat : ")
Hobby = input("Hobby : ")
Number = input("No. HP : ")

print("Nama \t\t\t: ", Name)
print("NIM \t\t\t: ", NIM)
print("Kelas Paralel \t\t: ", Class)
print("Tempat/Tanggal Lahir \t: ", TTL)
print("Alamat \t\t\t: ", Address)
print("Hobby \t\t\t: ", Hobby)
print("No. HP \t\t\t: ", Number)
